import 'package:flutter/material.dart';

class CustomIcons {
  CustomIcons._();

  static const String? _fontPackage = null;
  static const String _ipLabel = 'Ip';
  static const String _portLabel = 'Port';
  static const String _portsLabel = 'Ports';
  static const String _logoLabel = 'Logo';
  static const String _arcadeLabel = 'Arcade';
  static const String _miscLabel = 'Misc';
  static const String _retropieLabel = 'Retropie';
  static const String _recalboxLabel = 'Recalbox';
  static const String _batoceraLabel = 'Batocera';
  static const String _homeLabel = 'Home';
  static const String _portableLabel = 'Portable';
  static const String _computerLabel = 'Computer';
  static const String _lakkaLabel = 'Lakka';

  static const IconData ip = IconData(
    0xe800,
    fontFamily: _ipLabel,
    fontPackage: _fontPackage,
  );
  static const IconData port = IconData(
    0xe801,
    fontFamily: _portLabel,
    fontPackage: _fontPackage,
  );
  static const IconData ports = IconData(
    0xe804,
    fontFamily: _portsLabel,
    fontPackage: _fontPackage,
  );
  static const IconData logo = IconData(
    0xe801,
    fontFamily: _logoLabel,
    fontPackage: _fontPackage,
  );
  static const IconData arcade = IconData(
    0xe803,
    fontFamily: _arcadeLabel,
    fontPackage: _fontPackage,
  );
  static const IconData misc = IconData(
    0xe802,
    fontFamily: _miscLabel,
    fontPackage: _fontPackage,
  );
  static const IconData retropie = IconData(
    0xe800,
    fontFamily: _retropieLabel,
    fontPackage: _fontPackage,
  );
  static const IconData recalbox = IconData(
    0xe801,
    fontFamily: _recalboxLabel,
    fontPackage: _fontPackage,
  );
  static const IconData batocera = IconData(
    0xe802,
    fontFamily: _batoceraLabel,
    fontPackage: _fontPackage,
  );
  static const IconData home = IconData(
    0xe801,
    fontFamily: _homeLabel,
    fontPackage: _fontPackage,
  );
  static const IconData portable = IconData(
    0xe805,
    fontFamily: _portableLabel,
    fontPackage: _fontPackage,
  );
  static const IconData computer = IconData(
    0xe801,
    fontFamily: _computerLabel,
    fontPackage: _fontPackage,
  );
  static const IconData lakka = IconData(
    0xe803,
    fontFamily: _lakkaLabel,
    fontPackage: _fontPackage,
  );

  static const Map<String, IconData> imageMap = {
    "3do": CustomIcons.home,
    "3ds": CustomIcons.portable,
    "64dd": CustomIcons.home,
    "abuse": CustomIcons.ports,
    "adam": CustomIcons.computer,
    "advision": CustomIcons.home,
    "amiga1200": CustomIcons.computer,
    "amiga500": CustomIcons.computer,
    "amiga600": CustomIcons.computer,
    "amigacd32": CustomIcons.home,
    "amigacdtv": CustomIcons.home,
    "amstradcpc": CustomIcons.computer,
    "apfm1000": CustomIcons.home,
    "apple2": CustomIcons.computer,
    "apple2gs": CustomIcons.computer,
    "arcade": CustomIcons.arcade,
    "arcadia": CustomIcons.home,
    "archimedes": CustomIcons.computer,
    "arduboy": CustomIcons.portable,
    "astrocde": CustomIcons.home,
    "atari2600": CustomIcons.home,
    "atari5200": CustomIcons.home,
    "atari7800": CustomIcons.home,
    "atari800": CustomIcons.computer,
    "atarilynx": CustomIcons.portable,
    "atarist": CustomIcons.computer,
    "atom": CustomIcons.computer,
    "atomiswave": CustomIcons.arcade,
    "bbc": CustomIcons.computer,
    "bbcmicro": CustomIcons.computer,
    "bk": CustomIcons.computer,
    "boom3": CustomIcons.ports,
    "c128": CustomIcons.computer,
    "c20": CustomIcons.computer,
    "c64": CustomIcons.computer,
    "camplynx": CustomIcons.computer,
    "cannonball": CustomIcons.ports,
    "cavestory": CustomIcons.ports,
    "cdi": CustomIcons.home,
    "cdogs": CustomIcons.ports,
    "cgenius": CustomIcons.computer,
    "channelf": CustomIcons.home,
    "chihiro": CustomIcons.arcade,
    "coco": CustomIcons.computer,
    "coleco": CustomIcons.home,
    "colecovision": CustomIcons.home,
    "commanderx16": CustomIcons.computer,
    "corsixth": CustomIcons.computer,
    "cplus4": CustomIcons.computer,
    "crvision": CustomIcons.home,
    "daphne": CustomIcons.arcade,
    "devilutionx": CustomIcons.ports,
    "doom3": CustomIcons.ports,
    "dos": CustomIcons.computer,
    "dragon": CustomIcons.computer,
    "dreamcast": CustomIcons.home,
    "dxx-rebirth": CustomIcons.computer,
    "easyrpg": CustomIcons.ports,
    "ecwolf": CustomIcons.ports,
    "eduke32": CustomIcons.ports,
    "electron": CustomIcons.computer,
    "etlegacy": CustomIcons.ports,
    "fallout1-ce": CustomIcons.ports,
    "fallout2-ce": CustomIcons.ports,
    "fba": CustomIcons.arcade,
    "fbneo": CustomIcons.arcade,
    "fds": CustomIcons.home,
    "flash": CustomIcons.misc,
    "flatpak": CustomIcons.misc,
    "fm7": CustomIcons.computer,
    "fmtowns": CustomIcons.computer,
    "fpinball": CustomIcons.ports,
    "fury": CustomIcons.ports,
    "gamate": CustomIcons.portable,
    "gameandwatch": CustomIcons.portable,
    "gamecom": CustomIcons.portable,
    "gamecube": CustomIcons.home,
    "gamegear": CustomIcons.portable,
    "gamepock": CustomIcons.portable,
    "gb": CustomIcons.portable,
    "gb2players": CustomIcons.portable,
    "gba": CustomIcons.portable,
    "gbc": CustomIcons.portable,
    "gbc2players": CustomIcons.portable,
    "genesis": CustomIcons.home,
    "gmaster": CustomIcons.portable,
    "gong": CustomIcons.ports,
    "gp32": CustomIcons.portable,
    "gw": CustomIcons.portable,
    "gx4000": CustomIcons.home,
    "gzdoom": CustomIcons.ports,
    "hcl": CustomIcons.ports,
    "hurrican": CustomIcons.ports,
    "ikemen": CustomIcons.ports,
    "intellivision": CustomIcons.home,
    "iortcw": CustomIcons.ports,
    "jaguar": CustomIcons.home,
    "jaguarcd": CustomIcons.home,
    "jazz2": CustomIcons.ports,
    "laser310": CustomIcons.computer,
    "lcdgames": CustomIcons.portable,
    "lowresnx": CustomIcons.home,
    "lutro": CustomIcons.ports,
    "lynx": CustomIcons.portable,
    "macintosh": CustomIcons.computer,
    "mame": CustomIcons.arcade,
    "mame-libretro": CustomIcons.arcade,
    "mastersystem": CustomIcons.home,
    "megadrive": CustomIcons.home,
    "megaduck": CustomIcons.portable,
    "model1": CustomIcons.arcade,
    "model2": CustomIcons.arcade,
    "model3": CustomIcons.arcade,
    "moonlight": CustomIcons.misc,
    "mrboom": CustomIcons.ports,
    "msu-md": CustomIcons.home,
    "msx": CustomIcons.computer,
    "msx1": CustomIcons.computer,
    "msx2": CustomIcons.computer,
    "msx2+": CustomIcons.computer,
    "msxturbor": CustomIcons.computer,
    "mugen": CustomIcons.ports,
    "multivision": CustomIcons.home,
    "n64": CustomIcons.home,
    "n64dd": CustomIcons.home,
    "namco2x6": CustomIcons.arcade,
    "naomi": CustomIcons.arcade,
    "naomi2": CustomIcons.arcade,
    "naomigd": CustomIcons.arcade,
    "nds": CustomIcons.portable,
    "neogeo": CustomIcons.home,
    "neogeocd": CustomIcons.home,
    "nes": CustomIcons.home,
    "ngp": CustomIcons.portable,
    "ngpc": CustomIcons.portable,
    "o2em": CustomIcons.home,
    "odyssey2": CustomIcons.home,
    "openbor": CustomIcons.ports,
    "openjazz": CustomIcons.ports,
    "openlara": CustomIcons.ports,
    "oricatmos": CustomIcons.computer,
    "palm": CustomIcons.portable,
    "pc88": CustomIcons.computer,
    "pc98": CustomIcons.computer,
    "pcengine": CustomIcons.home,
    "pcenginecd": CustomIcons.home,
    "pcfx": CustomIcons.home,
    "pcv2": CustomIcons.portable,
    "pdp1": CustomIcons.computer,
    "pet": CustomIcons.computer,
    "pico": CustomIcons.home,
    "pico8": CustomIcons.home,
    "plugnplay": CustomIcons.misc,
    "pokemini": CustomIcons.portable,
    "ports": CustomIcons.misc,
    "prboom": CustomIcons.ports,
    "ps2": CustomIcons.home,
    "ps3": CustomIcons.home,
    "psp": CustomIcons.portable,
    "psvita": CustomIcons.portable,
    "psx": CustomIcons.home,
    "pv1000": CustomIcons.home,
    "pygame": CustomIcons.ports,
    "pyxel": CustomIcons.misc,
    "quake3": CustomIcons.ports,
    "raze": CustomIcons.ports,
    "reminiscence": CustomIcons.ports,
    "rott": CustomIcons.misc,
    "samcoupe": CustomIcons.computer,
    "satellaview": CustomIcons.home,
    "saturn": CustomIcons.home,
    "scummvm": CustomIcons.ports,
    "scv": CustomIcons.home,
    "sdlpop": CustomIcons.ports,
    "sega32x": CustomIcons.home,
    "segacd": CustomIcons.home,
    "sg-1000": CustomIcons.home,
    "sg1000": CustomIcons.home,
    "sgb": CustomIcons.home,
    "singe": CustomIcons.arcade,
    "snes": CustomIcons.home,
    "snes-msu1": CustomIcons.home,
    "socrates": CustomIcons.home,
    "solarus": CustomIcons.ports,
    "sonic-mania": CustomIcons.ports,
    "sonic3-air": CustomIcons.ports,
    "sonicretro": CustomIcons.ports,
    "spectravideo": CustomIcons.computer,
    "steam": CustomIcons.misc,
    "sufami": CustomIcons.home,
    "superbroswar": CustomIcons.ports,
    "supergrafx": CustomIcons.home,
    "supervision": CustomIcons.portable,
    "supracan": CustomIcons.home,
    "systemsp": CustomIcons.arcade,
    "theforceengine": CustomIcons.ports,
    "thextech": CustomIcons.ports,
    "thomson": CustomIcons.computer,
    "ti99": CustomIcons.computer,
    "ti994a": CustomIcons.computer,
    "tic80": CustomIcons.home,
    "triforce": CustomIcons.arcade,
    "trs80coco": CustomIcons.computer,
    "tutor": CustomIcons.computer,
    "tyrian": CustomIcons.ports,
    "tyrquake": CustomIcons.ports,
    "uqm": CustomIcons.ports,
    "uzebox": CustomIcons.home,
    "vc4000": CustomIcons.home,
    "vectrex": CustomIcons.home,
    "vg5000": CustomIcons.computer,
    "vgmplay": CustomIcons.misc,
    "vic20": CustomIcons.computer,
    "videopacplus": CustomIcons.home,
    "vircon32": CustomIcons.misc,
    "virtualboy": CustomIcons.home,
    "vis": CustomIcons.computer,
    "vitaquake2": CustomIcons.ports,
    "vpinball": CustomIcons.ports,
    "vsmile": CustomIcons.home,
    "wasm4": CustomIcons.home,
    "wii": CustomIcons.home,
    "wiiu": CustomIcons.home,
    "windows": CustomIcons.misc,
    "windows_installers": CustomIcons.misc,
    "wswan": CustomIcons.portable,
    "wswanc": CustomIcons.portable,
    "x1": CustomIcons.computer,
    "x68000": CustomIcons.computer,
    "xash3d_fwgs": CustomIcons.ports,
    "xbox": CustomIcons.home,
    "xbox360": CustomIcons.home,
    "xegs": CustomIcons.computer,
    "xrick": CustomIcons.ports,
    "zc210": CustomIcons.ports,
    "zmachine": CustomIcons.computer,
    "zx81": CustomIcons.computer,
    "zxspectrum": CustomIcons.computer,
  };
}
